declare module 'virtual:study-summaries' {
  /** Library-card projections of every bundled study, without `source`
   *  (the repository stamps that on). Generated by build/studySummariesPlugin. */
  const summaries: Omit<import('../../domain/study/types').StudySummary, 'source'>[]
  export default summaries
}
